---
apiVersion: v1
kind: Service
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app: media-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: media-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-mongodb
  labels:
    death-star-project: social-network
    app: media-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-mongodb
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: media-mongodb
      name: media-mongodb
    spec:
      containers:
      - name: media-mongodb
        image: mongo
        # args: ["--config", "/etc/mongo/mongod.conf"]
        volumeMounts:
          - name: my-data
            mountPath: /data/db
          # - name: config
          #   mountPath: /etc/mongo
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
      # - name: config
      #   configMap:
      #     name: mongodb-config
